# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Hidden Markov Model Parameter Estimation
#' @name hmm_em
NULL

hmm_em <- function(observations, n_states, dist_type = "normal", max_iter = 100L) {
    .Call('_wpfSA24204165_hmm_em', PACKAGE = 'wpfSA24204165', observations, n_states, dist_type, max_iter)
}

